function foodFalling () {
    if (true) {
        falling = sprites.create(list[randint(0, list.length - 0)], SpriteKind.Projectile)
    }
    falling.y = -10
    falling.x = randint(0, 160)
    falling.vy = 20
}
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    Michael.x += -5
})
info.onCountdownEnd(function () {
    game.over(true, effects.confetti)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    Michael.x += 5
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    otherSprite.destroy()
    info.changeScoreBy(1)
})
let list: Image[] = []
let falling: Sprite = null
let Michael: Sprite = null
class ActionKind {
    static Walking = 0
    static Idle = 1
    static Jumping = 2
    static walk_right = 3
}
scene.setBackgroundImage(img`
    dddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbddcdddddddddddddddddddddddcbbbbbdddddddddddddddd
    ddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddcdddddddddddddddddddddddcbbbbddddddddddddddddd
    dddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbddddcdddddddddddddddddddddddcbbddddddddddddddddddd
    ddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddcdddddddddddddddddddddddcbbddddddddddddddddddd
    dddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbddddddcdddddddddddddddddddddddcbdddddddddddddddddddd
    ddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddcdddddddddddddddddddddddcbdddddddddddddddddddd
    dddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbddddddddcdddddddddddddddddddddddcddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcdddddddddddddddddddddbdcdbddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcdddddddddddddddddddddbdcdbddddddddddddddddddd
    dddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbddddddddcdddddddddddddddddddddbdcdbddddddddddddddddddd
    ddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddcdddddddddddddddddddddbdcdbddddddddddddddddddd
    dddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbddddddcdddddddddddddddddddddbdcdbddddddddddddddddddd
    ddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddcdddddddddddddddddddddbdcdbddddddddddddddddddd
    dddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbddddcdddddddddddddddddddddbdcdbddddddddddddddddddd
    ddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddcbddddddddddddddddddddbdcdbddddddddddddddddddd
    dddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbddcbddddddddddddddddddddbdcdbddddddddddddddddddd
    ddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddcbddddddddddddddddddddbdcdbddddddddddddddddddd
    dddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbddddcbbdddddddddddddddddddbdcdbddddddddddddddddddd
    ddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddcbbdddddddddddddddddddbdcdbddddddddddddddddddd
    dddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbddddddcbbdddddddddddddddddddbdcdbddddddddddddddddddd
    ddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddcbbdddddddddddddddddddbdcdbddddddddddddddddddd
    dddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbddddddddcbbdddddddddddddddddddbdcdbddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcbbdddddddddddddddddddbdcdbddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcbbdddddddddddddddddddbdcdbddddddddddddddddddd
    dddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbddddddddcbbbddddddddddddddddddbdcdbddddddddddddddddddd
    ddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddcbbbddddddddddddddddddbdcdbddddddddddddddddddd
    dddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbddddddcbbbbdddddddddddddddddddcddddddddddddddddddddd
    ddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddcbbbbddddddddddddddccdddcdddccdddddddddddddddd
    dddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbddddcbbbbbddddddddddddceecddcddceecddddddddddddddd
    ddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddcbbbbbbdddddddddddceecddcddceecddddddddddddddd
    dddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbddcbbbbbbbdddddddddddccdddcdddccdddddddddddddddd
    ddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddcbbbbbbbbdddddddddddddddcddddddddddddddddddddd
    dddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbddddcbbbbbbbbbddddddddddddddcddddddddddddddddddddd
    ddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbddddddccccccccccccccccccccccccccccccccccccccccccccc
    dddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddccccccddbbbbbdddddddddddbbbbbdddddddceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    ddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbddddccccccdddbbbdddddddddddddbbbddddddddceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    dddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddccccccddddbdddddddddddddddbdddddddddceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddc999999cdddddddddddddddddddddddddddddceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddc999999cdddddddddddddddddddddddddddddceeeeeeeeeeebbbbbbeeeeeeeeeebbbbbbbbbbbbbbbbb
    dddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddcccddddc999999cdddbdddddddddddddddbdddddddddccccccccccccccccccccccccccccccccccccccccccccc
    ddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbddddddddddddcccbdddc999999cddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbddddd
    dddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbddddddddddcccccbddc111111cdbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddd
    ddddddbbbbbbbddccccccccccccccccccccccccccccccccccdddddbbbbbbbdddddddddc999cbbdc111111cbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbddd
    dddddbbbbbbbbbccddddddddddddddddddddddddddddddddccdddbbbbbbbbbdddddddbc999cbbbc111111cbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdd
    ddddbbbbbbbbbccddddddddddddddddddddddddddbbbbddddccdbbbbbbbbbbbdddddbbc999cbbbc111111cbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbd
    dddbbbbbbbbbbcdddddddddddddddddddddddddddddbbbbdddcbbbbbbbbbbbbbdddbbbc666cbbbc111111cbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbb
    ddddbbbbbbbbbcddddddddddddddddddddddddddddddddbbbdcdbbbbbbbbbbbdddddbbc666cbbbc111111cbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbd
    dddddbbbbbbbbcdddddddddddddddddddddddddddddddddbbdcddbbbbbbbbbdddddddbc666cbbbc111111cbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdd
    ddddddbbbbbbbcdbbdbdddddddddddddddddddddddddddddbdcdddbbbbbbbdddddddddc666cbbdc111111cbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbddd
    dddddddbbbbbdcdbbdddddddddddddddddddddddddddddddbdcddddbbbbbddddddddccccccccccccccccccccbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddd
    ddddddddbbbddcdbbdbdddddddddddddddddddddddddddddbdcdddddbbbddddddddccccccccccccccccccccccbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbddddd
    dddddddddbdddcdbbdbdddddddddddddddddddddddddddddbdcddddddbddddddddddccccccccccccccccccccdbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddd
    dddddddddddddcdbbdddddddddddddddddddddddddddddddddcddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddcdbbdddddddddddddddddddddddddddddddddcddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddbdddcdbbbddddddddddddddddddddddddddddddddcddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddd
    ddddddddbbbddcdbbbbdddddddddddddddddddddddddddddddcdddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbddddd
    dddddddbbbbbdcdbbbbbddddddddddddddddddddddddddddddcddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddd
    ddddddbbbbbbbcdbdbbbbbbbbdddddddddddddddddddddddddcdddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbddd
    dddddbbbbbbbbcdbddbbbbbbbbdbbbddbdddddddddddddddddcddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdd
    ddddbbbbbbbbbcdbddddddddddddddddddddddddddddddddddcdbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbd
    dddbbbbbbbbbbcdbddccccccccccccccccccccccccccccddddcbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbbdddbbbbbbbbbbbbb
    ddddbbbbbbbbbcdbdcbbbbbbbbbbbbbbbbbbbbbbbbbbbbcdddcdbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbdddddbbbbbbbbbbbd
    dddddbbbbbbbbcdbddccccccccccccccccccccccccccccddddcddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdd
    ddddddbbbbbbbcddddddddddddddddddddddddddddddddddddcdddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbddd
    dddddddbbbbbdccccccccccccccccccccccccccccccccccccccddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddd
    ddddddddbbbddcddddddddddddddddddddddddddddddddddddcdddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbddddd
    dddddddddbdddcddddccccccccccccccccccccccccccccddddcddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddd
    dddddddddddddcdddcbbbbbbbbbbbbbbbbbbbbbbbbbbbbcdddcddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddddddcddddccccccccccccccccccccccccccccddddcddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    dddddddddbdddcddddddddddddddddddddddddddddddddddddcddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddddddddddddbdddddd
    ddddddddbbbddcdbddddddddddddddddddddddddddddddddddcdddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbdddddddddddddbbbddddd
    dddddddbbbbbdcdbddddddddddddddddddddddddddddddddddcddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddddddddddbbbbbdddd
    ddddddbbbbbbbcdbdddddddddddddcccddddddddddddddddddcdddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbdddddddddbbbbbbbddd
    dddddbbbbbbbbcdbdddddddddddcccccccddddddddddddddddcddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdddddddbbbbbbbbbdd
    ccccccccccccccdbdddddddddddc1ccc1cddddddddddddddddcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    aaaaaaaaaaaaacdbdddddddddddc11111cddddddddddddddddcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaacdbdccccccddddc11111cddddccccccddddddcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    ccccccccccccccdbdc9999cddddc11111cddddc3333cddddddcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    aacaaaaacaaaacdbdc9c99cddddc11111cddddc3333cddddddcaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaacaa
    aacaaaaacaaaacdbdc9cc9cddddcccccccddddc3333cddddddcaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaaacaaaacaa
    aacaaaaacaaaacdbdc9999cdddddddddddddddc3333cddddddcaaaaacaaaaacaaaaacaaaaacaaacccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaaacaa
    aacaaaaacaaaacdbdc999cddddddddddddddddccccccddddddcaaaaacaaaaacaaaaacaaaaacaaacdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcaaaacaa
    aacaaaaacaaaacdbdc99cdddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaaacaa
    aacaaaaacaaaacdbdcccddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcaaaacaa
    aacaaaaacaaaacdbddddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacdcccccccdddddddddddddddddddddddddddddddddddddddddddddddddddddddddcccccccdcaaaacaa
    aacaaaaacaaaacdbddddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacddcccccddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddcccccddcaaaacaa
    aacaaaaacaaaacdbbdddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcaaaacaa
    aacaaaaacaaaacdbbbddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaaacaa
    aacaaaaacaaaacdbbbddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbbbbbbddddddddddddcbbbbddddddddddddddcbbbbdddddddddddddcbbbdddddddddddddbcaaaacaa
    aacaaaaacaaaacdbbbddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbbbbddddddddddddddcbbddddddddddddddddcbbbddddddddddddddcbbddddddddddddddbcaaaacaa
    aacaaaaacaaaacdbbbddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbbbddddddddddccdddcbdccddddddddddddddcbbdddddddddddccddcbdccddddddddddddbcaaaacaa
    aacaaaaacaaaacdbbbddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbbbdddddddddceecddcbceecdddddddddddddcbdddddddddddceecdcbceecdddddddddddbcaaaacaa
    aacaaaaacaaaacdbbbddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbbddddddddddceecddcbceecdddddddddddddcbdddddddddddceecdcbceecdddddddddddbcaaaacaa
    aacaaaaacaaaacdbbbddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbbdddddddddddccdddcbdccddddddddddddddcbddddddddddddccddcddccddddddddddddbcaaaacaa
    aacaaaaacaaaacdbbbddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbdddddddddddddddddcbdddddddddddddddddcbddddddddddddddddcddddddddddddddddbcaaaacaa
    aacaaaaacaaaacdbbbddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbdddddddddddddddddcbdddddddddddddddddcbddddddddddddddddcddddddddddddddddbcaaaacaa
    aacaaaaacaaaacdbbbddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbdddddddddddddddddcbdddddddddddddddddcdddddddddddddddddcddddddddddddddddbcaaaacaa
    aacaaaaacaaaacdbbbddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbdddddddddddddddddcbdddddddddddddddddcdddddddddddddddddcddddddddddddddddbcaaaacaa
    aacaaaaacaaaacdbbbddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbdddddddddddddddddcbdddddddddddddddddcdddddddddddddddddcddddddddddddddddbcaaaacaa
    aacaaaaacaaaacdbbbddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbdddddddddddddddddcbdddddddddddddddddcdddddddddddddddddcddddddddddddddddbcaaaacaa
    aacaaaaacaaaacdbbbddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbdddddddddddddddddcbdddddddddddddddddcdddddddddddddddddcddddddddddddddddbcaaaacaa
    aacaaaaacaaaacdbbbddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbdddddddddddddddddcddddddddddddddddddcdddddddddddddddddcdddddddddddddddddcaaaacaa
    aacaaaaacaaaacdbbbddddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbdddddddddddddddddcddddddddddddddddddcdddddddddddddddddcdddddddddddddddddcaaaacaa
    aacaaaaacaaaacdbbbbdddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbdddddddddddddddddcddddddddddddddddddcdddddddddddddddddcdddddddddddddddddcaaaacaa
    aacaaaaacaaaacdbbbbbddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbdddddddddddddddddcddddddddddddddddddcdddddddddddddddddcdddddddddddddddddcaaaacaa
    aacaaaaacaaaacdbbbbbddddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbdddddddddddddddddcddddddddddddddddddcdddddddddddddddddcdddddddddddddddddcaaaacaa
    aacaaaaacaaaacdbbbbbbdddddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbdddddddddddddddddcddddddddddddddddddcdddddddddddddddddcdddddddddddddddddcaaaacaa
    aacaaaaacaaaacdbbbbbbbbbddddddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbdddddddddddddddddcddddddddddddddddddcdddddddddddddddddcdddddddddddddddddcaaaacaa
    aacaaaaacaaaacdbbbbbbbbbbbbdddddddddddddddddddddddcaaaaacaaaaacaaaaacaaaaacaaacbdddddddddddddddddcddddddddddddddddddcdddddddddddddddddcdddddddddddddddddcaaaacaa
    ccccccccccccccddbbbbbbbbbbbbbbbbbbbbbbddddddddddddcccccccccccccccccccccccccccccbdddddddddddddddddcddddddddddddddddddcdddddddddddddddddcdddddddddddddddddcccccccc
    aaaaaaaaaaaaacdddbbbbbbbbbbbbbbbbbbbbbbbbbddddddddcaaaaaaaaaaaaaaaaaaaaaaaaaaacddddddddddddddddddcddddddddddddddddddcdddddddddddddddddcdddddddddddddddddcaaaacaa
    aaaaaaaaaaaaacddddddddddddddddddddddddddddddddddddcaaaaaaaaaaaaaaaaaaaaaaaaaaacddddddddddddddddddcddddddddddddddddddcdddddddddddddddddcdddddddddddddddddcaaaacaa
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    eedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceedddceddd
    eeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeeedceeed
    eeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeee
    cccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccccdcccc
    eeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeee
    eeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeee
    eeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeeeeceeee
    `)
tiles.setTilemap(tilemap`level2`)
game.showLongText(" Welcome to food fall !", DialogLayout.Top)
game.showLongText("Your objective is to catch as many falling food items in 60 seconds. Good luck!", DialogLayout.Top)
info.setScore(0)
Michael = sprites.create(img`
    ..................
    ..................
    ..................
    .ffffffffffffffff.
    .f51155555555555f.
    .f33333333333333f.
    .f51155555555555f.
    .f31155555555555f.
    ..f535555555555f..
    ...f5353535555f...
    ....f53535355f....
    .....ffffffff.....
    .......ffff.......
    .....ffffffff.....
    ....ffffffcfff....
    ...ffffffccfffc...
    ...fffcfffffffc...
    ...cccfffeeffcc...
    ...fffffeeffccf...
    ...fffbfeefbfff...
    ....f41f44f14f....
    ....fe444444ef....
    ....fffeeeefff....
    ...fefb7777bfef...
    ...e4f777777f4e...
    ...eef666666fee...
    ......ffffff......
    ......ff..ff......
    `, SpriteKind.Player)
falling = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Projectile)
Michael.setPosition(80, 103)
Michael.setFlag(SpriteFlag.StayInScreen, true)
info.startCountdown(60)
list = [
assets.image`apple`,
assets.image`burger`,
assets.image`cake`,
assets.image`chicken`,
assets.image`donut`,
assets.image`pizza`,
assets.image`strawberry`,
assets.image`taco`
]
game.onUpdateInterval(3200, function () {
    foodFalling()
})
